# Generated by Django 5.2.17 on 2026-08-15 09:28

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('Current/Checking', 'Current/Checking'), ('Savings/Deposit', 'Savings/Deposit'), ('Investment/Brokerage', 'Investment/Brokerage'), ('Pension/Retirement', 'Pension/Retirement'), ('Property', 'Property'), ('Physical Asset', 'Physical Asset'), ('Credit Card', 'Credit Card'), ('Loan/Mortgage', 'Loan/Mortgage'), ('Other Liability', 'Other Liability')], max_length=32)),
                ('liquidity_tier', models.CharField(choices=[('Instant', 'Instant'), ('Short', 'Short'), ('Long', 'Long'), ('Locked', 'Locked')], max_length=16)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Dormant', 'Dormant'), ('Closed', 'Closed')], default='Open', max_length=8)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('AUD', 'Australian Dollar'), ('MYR', 'Malaysian Ringgit')], max_length=3)),
                ('opened_month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a reporting month as YYYY-MM.', regex=re.compile('^\\d{4}-(0[1-9]|1[0-2])$'))])),
                ('closed_month', models.CharField(blank=True, default=None, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a reporting month as YYYY-MM.', regex=re.compile('^\\d{4}-(0[1-9]|1[0-2])$'))])),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'opened_month'], name='accounts_status_opened')],
                'constraints': [models.CheckConstraint(condition=models.Q(('opened_month__regex', '^\\d{4}-(0[1-9]|1[0-2])$')), name='accounts_opened_month_is_a_month'), models.CheckConstraint(condition=models.Q(('closed_month__isnull', True), ('closed_month__regex', '^\\d{4}-(0[1-9]|1[0-2])$'), _connector='OR'), name='accounts_closed_month_is_a_month'), models.CheckConstraint(condition=models.Q(('closed_month__isnull', True), ('closed_month__gte', models.F('opened_month')), _connector='OR'), name='accounts_closed_not_before_opened'), models.CheckConstraint(condition=models.Q(models.Q(('closed_month__isnull', False), ('status', 'Closed')), models.Q(models.Q(('status', 'Closed'), _negated=True), ('closed_month__isnull', True)), _connector='OR'), name='accounts_closed_status_has_a_closing_month')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a reporting month as YYYY-MM.', regex=re.compile('^\\d{4}-(0[1-9]|1[0-2])$'))])),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounts.account')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['account', '-month'], name='accounts_balance_acct_month'), models.Index(fields=['month'], name='accounts_balance_month')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'month'), name='accounts_one_balance_per_account_per_month'), models.CheckConstraint(condition=models.Q(('month__regex', '^\\d{4}-(0[1-9]|1[0-2])$')), name='accounts_balance_month_is_a_month')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
