# Generated by Django 5.2.17 on 2026-08-15 11:24

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_currency_immutable_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(blank=True, default='', max_length=32)),
                ('instrument_type', models.CharField(choices=[('Equity', 'Equity'), ('ETF', 'ETF'), ('Fund', 'Managed Fund'), ('Bond', 'Bond'), ('Other', 'Other')], default='Equity', max_length=16)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('AUD', 'Australian Dollar'), ('MYR', 'Malaysian Ringgit')], max_length=3)),
                ('estimated_tax_percent', models.DecimalField(blank=True, decimal_places=10, default=None, help_text="Indicative only. Not a calculation, and not any jurisdiction's rules.", max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(help_text='Holdings are scoped to one account. This cannot be changed later.', on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='accounts.account')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('action', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Split', 'Split'), ('Distribution', 'Distribution'), ('Reinvestment', 'Reinvestment')], max_length=16)),
                ('date', models.DateField()),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('unit_price', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('fees', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('split_ratio', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('cash_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.holding')),
            ],
            options={
                'ordering': ['-date', '-sequence', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'name'), name='investments_one_holding_per_name_per_account'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_tax_percent__isnull', True), ('estimated_tax_percent__gte', 0), _connector='OR'), name='investments_tax_percent_not_negative'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['holding', 'date', 'sequence'], name='investments_replay_order'),
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='investments_quantity_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('fees__gte', 0)), name='investments_fees_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('split_ratio__gte', 0)), name='investments_split_ratio_not_negative'),
        ),
    ]
