# Generated by Django 5.2.17 on 2026-08-15 11:06

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_currency_immutable_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='cashflow.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['direction', 'position', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecurringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('AUD', 'Australian Dollar'), ('MYR', 'Malaysian Ringgit')], max_length=3)),
                ('direction', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=8)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], max_length=12)),
                ('start_month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a month as YYYY-MM.', regex=re.compile('^\\d{4}-(0[1-9]|1[0-2])$'))])),
                ('end_month', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a month as YYYY-MM.', regex=re.compile('^\\d{4}-(0[1-9]|1[0-2])$'))])),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_templates', to='cashflow.category')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecurringDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('period', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a month as YYYY-MM.', regex=re.compile('^\\d{4}-(0[1-9]|1[0-2])$'))])),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='cashflow.recurringtemplate')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('AUD', 'Australian Dollar'), ('MYR', 'Malaysian Ringgit')], max_length=3)),
                ('direction', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('import_batch', models.UUIDField(blank=True, help_text='Optional. Captured for Phase 2; read by no v1 report.', null=True)),
                ('recurring_period', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a month as YYYY-MM.', regex=re.compile('^\\d{4}-(0[1-9]|1[0-2])$'))])),
                ('account', models.ForeignKey(blank=True, help_text='Optional. Captured for Phase 2; read by no v1 report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_transactions', to='accounts.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cashflow.category')),
                ('recurring_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed', to='cashflow.recurringtemplate')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='cashflow_cat_parent_active'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('parent', 'name'), name='cashflow_unique_child_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=('name', 'direction'), name='cashflow_unique_parent_name_per_direction'),
        ),
        migrations.AddConstraint(
            model_name='recurringtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cashflow_template_amount_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('start_month__regex', '^\\d{4}-(0[1-9]|1[0-2])$')), name='cashflow_template_start_is_a_month'),
        ),
        migrations.AddConstraint(
            model_name='recurringdismissal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('template', 'period'), name='cashflow_one_dismissal_per_period'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date'], name='cashflow_txn_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', '-date'], name='cashflow_txn_cat_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['recurring_template', 'recurring_period'], name='cashflow_txn_recurring'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cashflow_amount_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('recurring_period__isnull', True), ('recurring_period__regex', '^\\d{4}-(0[1-9]|1[0-2])$'), _connector='OR'), name='cashflow_recurring_period_is_a_month'),
        ),
    ]
