# Generated by Django 5.2.17 on 2026-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_seed_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtemplate',
            name='currency',
            field=models.CharField(choices=[('USD', 'United States Dollar'), ('AUD', 'Australian Dollar'), ('MYR', 'Malaysian Ringgit'), ('XAU', 'Gold (Troy Ounce)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'United States Dollar'), ('AUD', 'Australian Dollar'), ('MYR', 'Malaysian Ringgit'), ('XAU', 'Gold (Troy Ounce)')], max_length=3),
        ),
    ]
