# Generated by Django 5.2.17 on 2026-08-15 05:07

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('currency', models.CharField(choices=[('AUD', 'Australian Dollar'), ('MYR', 'Malaysian Ringgit')], max_length=3)),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=10, max_digits=19)),
                ('source', models.CharField(choices=[('entered', 'Entered by hand'), ('api', 'Fetched from a provider'), ('carried', 'Materialised from a carry-forward')], default='entered', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-rate_date', 'currency'],
                'indexes': [models.Index(fields=['currency', '-rate_date'], name='fx_rate_pair_date_desc')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('currency', 'rate_date'), name='fx_one_rate_per_pair_per_date'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='fx_rate_is_positive'), models.CheckConstraint(condition=models.Q(('currency', 'USD'), _negated=True), name='fx_no_rate_for_the_base_against_itself')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
