# Generated by Django 5.2.17 on 2026-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar'), ('MYR', 'Malaysian Ringgit'), ('XAU', 'Gold (Troy Ounce)')], max_length=3),
        ),
    ]
