# Generated by Django 5.2.17 on 2026-08-15 05:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('reporting_currency', models.CharField(choices=[('USD', 'United States Dollar'), ('AUD', 'Australian Dollar'), ('MYR', 'Malaysian Ringgit')], default='USD', help_text='Display only. The base and stored currency is always USD.', max_length=3)),
                ('timezone', models.CharField(default='Asia/Kuala_Lumpur', max_length=64)),
                ('rate_staleness_days', models.PositiveSmallIntegerField(default=7, help_text='A rate more than this many days old is flagged stale.', validators=[django.core.validators.MinValueValidator(1)])),
                ('rate_variance_percent', models.DecimalField(decimal_places=10, default=Decimal('10'), help_text='Advisory threshold for a rate that jumps against its predecessor.', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='core_settings_is_singleton'), models.CheckConstraint(condition=models.Q(('rate_staleness_days__gte', 1)), name='core_settings_staleness_positive'), models.CheckConstraint(condition=models.Q(('rate_variance_percent__gt', 0)), name='core_settings_variance_positive')],
            },
        ),
    ]
